server.port=8080

spring.application.name=feewaiver-sb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=prod

fluxnova.bpm.admin-user.id=demo
fluxnova.bpm.admin-user.password=demo
fluxnova.bpm.admin-user.firstName=Demo
fluxnova.bpm.admin-user.lastName=User
fluxnova.bpm.filter.create=All Tasks

# Enable all actuator beans (OK without security for development on a firewalled system).
management.endpoints.web.exposure.include=*

# Set all logging for this application to the debug level.
logging.level.co.summit58.feewaiver.sb=DEBUG

# Allow for detailed Job Executor logging (including the display of OLE's).
#logging.level.org.fluxnova.bpm.engine.jobexecutor=DEBUG

#Ollama
ollama.base-url=http://localhost:11434
ollama.chat-path=/api/chat
ollama.model=mistral-small

app.analysis.base-url=http://localhost:8080
