name: Build and Publish Docker Image

env:
  DOCKER_USERNAME: finos
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Java setup
        uses: ./.github/actions/java-setup

      - name: Configure git
        uses: ./.github/actions/configure-git

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          theme: dark

      - name: Build with Maven
        run: mvn clean install -f fluxnova-springboot-example/pom.xml

      - name: Extract version from branch
        id: version
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          VERSION="${GITHUB_REF#refs/heads/release/}"
          echo "release_tag=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and publish Docker image
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: ./.github/actions/build-publish-image
        with:
          image_name: finos/fluxnova-bpm-platform
          dockerfile_path: fluxnova-springboot-example/Dockerfile
          docker_context: .
          release_tag: ${{ steps.version.outputs.release_tag }}
